spring.application.name=Sound-Production
# --- DATABASE CONFIG ---
spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.qtcgxqbkqsxtmeikiryi
spring.datasource.password=Muhamed 100
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA CONFIG ---
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

JWT_SECRET=mysuperlongsecretkey12345678901234567890